apiVersion: v1
kind: Service
metadata:
  name: codearts-webapp-service
spec:
  selector:
    app: codearts-webapp
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080